configData = {
  numChatMax        : 20,
  personalColor     : true,
  badgeVisible      : true,
  badgeChannelId    : 0,
  themeURI          : "",
  theme             : "dokidoki",
  themeName         : "",
  msgExistDuration  : 0,
  msgAniDuration    : 0,
  debugLevel        : 2,
  useDisplayName    : true,
  loadCheerImgs     : true,
  loadTwitchCons    : true,
  loadTwitchv2      : true,
  loadDcCons        : true,
  dcConsURI         : "",
  subMonthsMsg      : "☆ {!0:{months} 개월 }구독{0: 시작}! ☆",
  cheersMsg         : "☆ {!0:{bits} 비트 }후원 ! ☆",
  clipReplaceMsg    : "[ 클립 ]",
  linkReplaceMsg    : "[ 링크 ]",
  webSocket         : "wss://irc-ws.chat.twitch.tv:443",
  nick              : "justinfan16831",
  pass              : "foobar",
  channel           : "#chowonhee1235",
  retryInterval     : 2,
  allMessageHandle  : false,
  muteUser          : ["Nightbot"],
  deleteBanMsg      : true,
  commands          : [
    {exe:"clear", msg:"!!clear"},
    {exe:"theme", msg:"!!theme"},
    {exe:"load", msg:"!!load"},
    {exe:"scale", msg:"!!scale"}
  ],
  replaceMsgs       : [
		{orig: /\*\*(.+?)\*\*/g,    to: '<b>$1</b>'},
		{orig: /\'\'(.+?)\'\'/gi,   to: '<i>$1</i>'},
		{orig: /__(.+?)__/gi,       to: '<u>$1</u>'},
		{orig: /\-\-(.+?)\-\-/gi,   to: '<s>$1</s>'},
		{orig: /~~(.+?)~~/gi,       to: '<del>$1</del>'},
		{orig: /\^\^(.+?)\^\^/gi,   to: '<sup>$1</sup>'},
		{orig: /,,(.+?),,/gi,       to: '<sub>$1</sub>'},
		{orig: /\[br\]/gi,          to: '<br />'},

		{orig: /^!(tts(f|m)|mijin|jinho|clara|matt|yuri|shinji|meimei|liangliang|carmen|jose|google|유리|신지|구글|sy|서연) (.+?)/,
                                to: '&lt;$1&gt; $3'},
//		{orig: /^!!tts/,          to: '{no_display}'},
//		{orig: /^![a-zA-Z]+/,     to: '{no_display}'},
		{orig: /^!(sr|ㄴㄱ|신청) /, to: '{no_display}'},

    {orig:/^!{1,2}[a-zA-Z]+/, to:"{no_display}"}     // 봇 호출 영문 메세지 미표시
  ]
};
