dcConsData = [
  {"name":"안녕.png",              "keywords":["안녕"],                                         "tags":["핑키빈콘"]},
  {"name":"왜모름.png",              "keywords":["왜모름"],                                         "tags":["핑키빈콘"]},
  {"name":"욵지.png",              "keywords":["욵지"],                                         "tags":["핑키빈콘"]},
  {"name":"ㄴㄴ.png",              "keywords":["ㄴㄴ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㄹㅇ.png",              "keywords":["ㄹㅇ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㅁㄹ.png",              "keywords":["ㅁㄹ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㅂㄹ.png",              "keywords":["ㅂㄹ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㅇㅈ.png",              "keywords":["ㅇㅈ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㅋㅋ.png",              "keywords":["ㅋㅋ"],                                         "tags":["핑키빈콘"]},
  {"name":"ㅗㅜㅑ.png",              "keywords":["ㅗㅜㅑ"],                                         "tags":["핑키빈콘"]},
  {"name":"개추.png",              "keywords":["개추"],                                         "tags":["핑키빈콘"]},
  {"name":"고고헛.png",              "keywords":["고고헛"],                                         "tags":["핑키빈콘"]},
  {"name":"구웨엑.png",              "keywords":["구웨엑"],                                         "tags":["핑키빈콘"]},
  {"name":"굿.png",              "keywords":["굿"],                                         "tags":["핑키빈콘"]},
  {"name":"나만운없어.png",              "keywords":["나만운없어"],                                         "tags":["핑키빈콘"]},
  {"name":"누렁.png",              "keywords":["누렁"],                                         "tags":["핑키빈콘"]},
  {"name":"돈주머니.png",              "keywords":["돈주머니"],                                         "tags":["핑키빈콘"]},
  {"name":"땀.png",              "keywords":["땀"],                                         "tags":["핑키빈콘"]},
  {"name":"물음표.png",              "keywords":["?"],                                         "tags":["핑키빈콘"]},
  {"name":"뷰지.png",              "keywords":["뷰지"],                                         "tags":["핑키빈콘"]},
  {"name":"비추.png",              "keywords":["비추"],                                         "tags":["핑키빈콘"]},
  {"name":"뽀송.png",              "keywords":["뽀송"],                                         "tags":["핑키빈콘"]},
  {"name":"뾰족귀.png",              "keywords":["비추"],                                         "tags":["핑키빈콘"]},
  {"name":"사망.png",              "keywords":["사망"],                                         "tags":["핑키빈콘"]},
  {"name":"싫름.png",              "keywords":["싫름"],                                         "tags":["핑키빈콘"]},
  {"name":"야호.png",              "keywords":["야호"],                                         "tags":["핑키빈콘"]},
  {"name":"어쩌라고.png",              "keywords":["어쩌라고"],                                         "tags":["핑키빈콘"]},
  {"name":"운빨충.png",              "keywords":["운빨충"],                                         "tags":["핑키빈콘"]},
  {"name":"응애.png",              "keywords":["응애"],                                         "tags":["핑키빈콘"]},
  {"name":"잘가.png",              "keywords":["잘가"],                                         "tags":["핑키빈콘"]},
  {"name":"저능아.png",              "keywords":["저능아"],                                         "tags":["핑키빈콘"]},
  {"name":"적셔.png",              "keywords":["적셔"],                                         "tags":["핑키빈콘"]},
  {"name":"질러.png",              "keywords":["질러"],                                         "tags":["핑키빈콘"]},
  {"name":"코코낸내.png",              "keywords":["코코낸내"],                                         "tags":["핑키빈콘"]},
  {"name":"크아악.png",              "keywords":["크아악"],                                         "tags":["핑키빈콘"]},
  {"name":"틀.png",              "keywords":["틀"],                                         "tags":["핑키빈콘"]},
  {"name":"푸하하.png",              "keywords":["푸하하"],                                         "tags":["핑키빈콘"]},
  {"name":"핑키빈분노.png",              "keywords":["핑키빈분노"],                                         "tags":["핑키빈콘"]},
  {"name":"한심.png",              "keywords":["한심"],                                         "tags":["핑키빈콘"]},
  {"name":"해명해.png",              "keywords":["해명해"],                                         "tags":["핑키빈콘"]},
  {"name":"호다닥.png",              "keywords":["호다닥"],                                         "tags":["핑키빈콘"]},
  {"name":"홍.png",              "keywords":["홍"],                                         "tags":["핑키빈콘"]},
  {"name":"힝힝.png",              "keywords":["힝힝"],                                         "tags":["핑키빈콘"]},
  {"name":"노랑이댄스.gif",              "keywords":["노랑이댄스","노랭이댄스"],                                         "tags":["디시콘"]},
  {"name":"주먹.gif",              "keywords":["주먹"],                                         "tags":["디시콘"]},
  {"name":"소멸.gif",              "keywords":["소멸"],                                         "tags":["디시콘"]},
  {"name":"엄.png",              "keywords":["엄","엄준식"],                                         "tags":["디시콘"]},
  {"name":"피.gif",              "keywords":["피"],                                         "tags":["디시콘"]},
  {"name":"보리스.png",              "keywords":["보리스"],                                         "tags":["디시콘"]},
  {"name":"어떤.png",              "keywords":["어떤"],                                         "tags":["디시콘"]},
  {"name":"구울.png",              "keywords":["구울"],                                         "tags":["디시콘"]},
  {"name":"대머리.gif",              "keywords":["대머리"],                                         "tags":["디시콘"]},
  {"name":"머머리.gif",              "keywords":["머머리"],                                         "tags":["디시콘"]},
  {"name":"스윗.png",              "keywords":["스윗"],                                         "tags":["디시콘"]},
  {"name":"안아줘.png",              "keywords":["안아줘","안아줘요"],                                         "tags":["디시콘"]}
	
	



];
